### ISSUE TITLE
About net -> com 수정해주세요!

### ISSUE THREAD

**Issue by WhiteHyun** [potados99/potados99.github.io#11]
제곧내입니다~!! 😁
blog.potados.com 인데 blog.potados.net으로 되어있어요

![image](https://user-images.githubusercontent.com/57972338/108199243-0c2ce500-7160-11eb-869a-27554973ebb6.png)

**Comment by potados99** [comment]
발견 못했었네요ㅠㅠ 감사합니다!!😆😆
